// Terms the speech model should expect in a Nigerian primary-care or HIV clinic.
// Sent as AssemblyAI keyterms_prompt (Universal-3.5 Pro: 1,000 words total, at most
// 6 words per phrase). The proxy re-checks those limits. Kept deliberately short:
// a list padded with rarely heard terms dilutes the boost for the ones that matter.
export const MEDICAL_KEYTERMS: string[] = [
  // HIV / TB programme
  'TLD',
  'dolutegravir',
  'tenofovir',
  'lamivudine',
  'efavirenz',
  'nevirapine',
  'zidovudine',
  'abacavir',
  'atazanavir',
  'lopinavir-ritonavir',
  'cotrimoxazole',
  'isoniazid',
  'TPT',
  'rifampicin',
  'pyrazinamide',
  'ethambutol',
  'viral load',
  'CD4',
  'ART',
  'PrEP',
  'PMTCT',
  'EAC',
  'MMD',
  'GeneXpert',
  'TB LAM',
  'sputum AFB',

  // Malaria and fever
  'artemether-lumefantrine',
  'artesunate',
  'dihydroartemisinin-piperaquine',
  'sulfadoxine-pyrimethamine',
  'amodiaquine',
  'malaria RDT',
  'malaria parasite',
  'blood film',
  'Widal',
  'typhoid',
  'enteric fever',

  // Antibiotics and common drugs
  'ceftriaxone',
  'ciprofloxacin',
  'amoxicillin',
  'amoxicillin-clavulanate',
  'azithromycin',
  'metronidazole',
  'doxycycline',
  'gentamicin',
  'fluconazole',
  'albendazole',
  'paracetamol',
  'ibuprofen',
  'diclofenac',
  'omeprazole',
  'salbutamol',
  'prednisolone',
  'chlorpheniramine',
  'ferrous sulphate',
  'folic acid',
  'oral rehydration salts',

  // Hypertension, diabetes, maternal
  'amlodipine',
  'lisinopril',
  'losartan',
  'nifedipine',
  'hydrochlorothiazide',
  'methyldopa',
  'metformin',
  'glibenclamide',
  'insulin',
  'magnesium sulphate',
  'oxytocin',
  'misoprostol',
  'pre-eclampsia',

  // Labs and investigations
  'PCV',
  'FBC',
  'HbA1c',
  'fasting blood sugar',
  'urinalysis',
  'urea and creatinine',
  'electrolytes',
  'liver function test',
  'HBsAg',
  'genotype',
];
